## Linear Algebra for AI and ML

### Assignment 2

### Question 10

### Shrinivas Khiste: 19CS30043

In [ ]:
from keras.datasets import mnist
import numpy as np
from sklearn.metrics import confusion_matrix

### Input Data

In [ ]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()
print("Train Shape: ",x_train.shape)
print("Test Shape: ",x_test.shape)

11501568/11490434 [==============================] - 0s 0us/step
Train Shape:  (60000, 28, 28)
Test Shape:  (10000, 28, 28)


In [ ]:
X = np.reshape(x_train,(60000,784))
Y = y_train

### Generating Train Data

In [ ]:
X_train = []
Y_train = []

In [ ]:
for dig in range(10):
  num = 0
  for i in range(len(Y)):
    if Y[i] == dig:
      X_train.append(X[i]/255)
      Y_train.append(dig)
      num += 1
    if num >= 1000:
      break

In [ ]:
X_train = np.array(X_train)
Y_train = np.array(Y_train)

In [ ]:
X_train.shape,Y_train.shape

((10000, 784), (10000,))

### Generating Test Data

In [ ]:
X_test = []
Y_test = []

In [ ]:
for dig in range(10):
  num = 0
  for i in range(len(Y)):
    if Y[i] == dig:
      X_test.append(X[i]/255)
      Y_test.append(dig)
      num += 1
    if num >= 100:
      break

In [ ]:
X_test = np.array(X_test)
Y_test = np.array(Y_test)

In [ ]:
X_test.shape,Y_test.shape

((1000, 784), (1000,))

### Fitting Least Square Classifier

Ax=b is equation for each digit

Rows of A will be image vectors, that is, X_train vector

b will be a 1 if that digit is present else -1

In [ ]:
y_confid = [[] for i in range(1000)]

In [ ]:
A_pseudo = np.linalg.pinv(X_train)

In [ ]:
for digit in range(10):
  b_=[]
  for i in range(len(Y_train)):
    if(Y_train[i]==digit):
      b_.append(1)
    else:
      b_.append(-1)
  b_dig = np.array(b_)
  b_dig = np.reshape(b_dig,(len(Y_train),1))

  theta = np.matmul(A_pseudo,b_dig)
  confid = np.matmul(X_test,theta)
  confid=confid.flatten()

  for i in range(1000):
    y_confid[i].append(confid[i])

In [ ]:
len(y_confid)

1000

In [ ]:
y_pred = [np.argmax(y) for y in y_confid]

### Confusion Matrix

In [ ]:
confMat = confusion_matrix(y_pred,Y_test,labels=[0,1,2,3,4,5,6,7,8,9])

In [ ]:
print(confMat)

[[97  1  1  0  0  0  1  1  0  1]
 [ 0 94  7  1  0  1  2  5  5  1]
 [ 1  1 79  2  0  1  1  1  1  0]
 [ 0  0  2 88  0 11  0  1  2  2]
 [ 0  1  1  0 93  2  1  2  1  6]
 [ 1  0  1  4  1 73  1  0  4  0]
 [ 1  0  3  0  1  2 94  0  0  0]
 [ 0  0  2  1  2  0  0 83  0  6]
 [ 0  3  3  1  1  6  0  1 85  2]
 [ 0  0  1  3  2  4  0  6  2 82]]


### Accuracy

In [ ]:
test_accuracy = 0
for i in range(10):
  test_accuracy+=confMat[i][i]

In [ ]:
print("Accuracy: "+str(test_accuracy/10)+"%")

Accuracy: 86.8%
